## Add an item
POST http://localhost:5000/api/items HTTP/1.1
content-type: application/json

{
  "name": "Crisps"
}


###


## Get all items
GET http://localhost:5000/api/items HTTP/1.1
content-type: application/json

###

## Delete an item by id
DELETE http://localhost:5000/api/items/5e8b4b85fe931826fe36c2b7 HTTP/1.1
content-type: application/json

###